### ISSUE TITLE
PS4 1.2 A, B, C

### ISSUE THREAD

**Issue by rebeccajohnson88** [rebeccajohnson88/qss20_slides_activities#28]
A. Using the original `pharma` press release (so the one before stripping punctuation/digits), use spaCy to extract all named entities from the press release.

B. Print the unique named entities with the tag: `LAW`

C. Use Google to summarize in one sentence what the `RICO` named entity means and why this might apply to a pharmaceutical case (and not just a mafia case...) 

**Output for unique named entities with tag LAW**:

![image](https://user-images.githubusercontent.com/21369316/153985423-4707ab7a-6445-4995-8dec-46ef12361f2c.png)

**Comment by afwojcik** [comment]
For part B, what form should the output be in? A list?

**Comment by rebeccajohnson88** [comment]
> For part B, what form should the output be in? A list?

whatever form is fine as long as content is same!

**Comment by emmaw219** [comment]
Should the output for part B be a collection of unique spacy entities or should it be only the string text of the entities? It looks like when I ask it to put the entire entity in a set, repeated names are included because they are not technically identical spacy entities so python sets allow including both, but it works when I ask it to only add the text of the entity to the set.

**Comment by rebeccajohnson88** [comment]
> Should the output for part B be a collection of unique spacy entities or should it be only the string text of the entities? It looks like when I ask it to put the entire entity in a set, repeated names are included because they are not technically identical spacy entities so python sets allow including both, but it works when I ask it to only add the text of the entity to the set.

text attribute of entity- thanks for checking!
